apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gozsja7mr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gozsja7mr-python 
  name: gozsja7mr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gozsja7mr-python 
